/**
 * PrCommentWriter — produces TURPAN_PR_COMMENT.md
 *
 * GitHub/PR-friendly markdown comment summarizing a diff review.
 * Designed to be posted directly as a PR comment.
 */

import { join } from 'path';
import type { TurpanAnalysisData } from './types.js';
import type { DiffReview } from './types.js';

export class PrCommentWriter {
  constructor(private data: TurpanAnalysisData) {}

  /** Write the PR comment and return the file path. */
  async write(runPath: string): Promise<string> {
    const { mkdirSync, writeFileSync } = await import('fs');
    const content = this.render();
    mkdirSync(runPath, { recursive: true });
    const dest = join(runPath, 'TURPAN_PR_COMMENT.md');
    writeFileSync(dest, content, 'utf-8');
    return dest;
  }

  render(): string {
    const { verdict, findings, scorecard, diffReview } = this.data;
    const critical = findings.filter(f => f.severity === 'critical').length;
    const high     = findings.filter(f => f.severity === 'high').length;
    const medium   = findings.filter(f => f.severity === 'medium').length;
    const low      = findings.filter(f => f.severity === 'low').length;

    const verdictIcon = verdict === 'GO' ? '✅' : verdict === 'CONDITIONAL_GO' ? '⚠️' : '❌';
    const verdictLabel = verdict === 'GO' ? 'GO' : verdict === 'CONDITIONAL_GO' ? 'CONDITIONAL GO' : verdict === 'NO_GO' ? 'NO GO' : 'INTERNAL ONLY';

    const lines: string[] = [];

    // No diff review — show message and fall back to standard header
    if (!diffReview) {
      lines.push('## 🐪 Turpan Review', '');
      lines.push('> Run with --from/--to flags for diff review', '');
      lines.push('');
      lines.push(`| Status | Score | Critical | High | Medium | Low |`);
      lines.push('|--------|-------|----------|------|--------|-----|');
      lines.push(`| ${verdictIcon} **${verdictLabel}** | ${scorecard.overall}/100 | ${critical} | ${high} | ${medium} | ${low} |`);
      lines.push('');
      if (findings.length > 0) {
        lines.push('### 🔎 Top Findings', '');
        const top = findings.slice(0, 10);
        for (const f of top) {
          const icon = f.severity === 'critical' ? '🔴' :
                       f.severity === 'high' ? '🟠' :
                       f.severity === 'medium' ? '🟡' : '🔵';
          lines.push(`${icon} **${f.severity.toUpperCase()}** \`[${f.category}]\` ${f.title}`);
          if (f.file) lines.push(`   └─ ${f.file}${f.line ? `:${f.line}` : ''}`);
        }
        lines.push('');
      }
      lines.push('---', '');
      lines.push('_🤖 Generated by [Turpan](https://github.com/turpan/turpan) — PR review agent_', '');
      return lines.join('\n');
    }

    // Merge decision banner (shown at top for block/request_changes)
    const md = diffReview.mergeDecision;
    if (md?.decision === 'block_merge') {
      lines.push('## ❌ MERGE BLOCKED', '');
      lines.push('> This PR has blocking issues that must be resolved before merge.', '');
      if (md.blockers.length > 0) {
        for (const b of md.blockers) lines.push(`- 🛑 ${b}`);
      }
      lines.push('');
    } else if (md?.decision === 'request_changes') {
      lines.push('## ⚠️ CHANGES REQUESTED', '');
      lines.push('> This PR has issues that should be addressed before merging.', '');
      if (md.warnings.length > 0) {
        for (const w of md.warnings) lines.push(`- ⚠️ ${w}`);
      }
      lines.push('');
    }

    // Header
    lines.push('## 🐪 Turpan Review', '');
    lines.push(`> Diff review of \`${diffReview.baseRef} → ${diffReview.targetRef}\` | Overall: **${scorecard.overall}/100**`, '');
    lines.push('');

    // Verdict badge
    lines.push(`| Status | Score | Critical | High | Medium | Low |`, '|--------|-------|----------|------|--------|-----|');
    lines.push(`| ${verdictIcon} **${verdictLabel}** | ${scorecard.overall}/100 | ${critical} | ${high} | ${medium} | ${low} |`);
    lines.push('');

    // Diff-specific recommendation
    const recIcon = diffReview.recommendation === 'approve' ? '✅' :
                    diffReview.recommendation === 'request_changes' ? '⚠️' : '❌';
    lines.push(`## ${recIcon} PR Decision: **${diffReview.recommendation.replace('_', ' ').toUpperCase()}**`, '');
    lines.push('');
    lines.push(diffReview.summary, '');
    lines.push('');

    // Changed files
    lines.push('### 📁 Changed Files', '');
    lines.push(diffReview.changedFilesSummary, '');
    lines.push('');

    // Risk summary
    const criticalRisk = diffReview.riskByFile.filter(f => f.risk === 'critical');
    const highRisk     = diffReview.riskByFile.filter(f => f.risk === 'high');
    if (criticalRisk.length > 0) {
      lines.push(`🔴 **Critical risk files:** ${criticalRisk.map(f => `\`${f.file}\``).join(', ')}`, '');
    }
    if (highRisk.length > 0) {
      lines.push(`🟠 **High risk files:** ${highRisk.map(f => `\`${f.file}\``).join(', ')}`, '');
    }
    if (criticalRisk.length === 0 && highRisk.length === 0) {
      lines.push('🟢 **No high/critical risk files detected.**', '');
    }
    lines.push('');

    // Changed routes/APIs/components
    if (diffReview.changedRoutes.length > 0) {
      lines.push('### 🛣️ Changed Routes', '');
      for (const r of diffReview.changedRoutes) lines.push(`- \`${r}\``);
      lines.push('');
    }
    if (diffReview.changedApis.length > 0) {
      lines.push('### 🔌 Changed APIs', '');
      for (const a of diffReview.changedApis) lines.push(`- \`${a}\``);
      lines.push('');
    }
    if (diffReview.changedComponents.length > 0) {
      lines.push('### 🧩 Changed Components', '');
      lines.push('| Component |', '|-----------|');
      for (const c of diffReview.changedComponents) lines.push(`| \`${c}\` |`);
      lines.push('');
    }

    // Top 5 Introduced Risks
    if (diffReview.topIntroducedRisks.length > 0) {
      lines.push('### 🚨 Top 5 Introduced Risks', '');
      const top5 = diffReview.topIntroducedRisks.slice(0, 5);
      for (const r of top5) {
        const severityLabel = r.severity.toUpperCase();
        const sevIcon = r.severity === 'critical' ? '🔴' :
                        r.severity === 'high' ? '🟠' :
                        r.severity === 'medium' ? '🟡' : '🔵';
        const location = r.file ? ` — \`${r.file}${r.line ? `:${r.line}` : ''}\`` : '';
        lines.push(`${sevIcon} **${severityLabel}** ${r.title}${location}`);
        if (r.explanation) lines.push(`   ${r.explanation}`);
      }
      lines.push('');
    }

    // Test Coverage Status
    if (diffReview.testCoverage) {
      const tc = diffReview.testCoverage;
      const statusIcon = tc.status === 'adequate' ? '✅' :
                         tc.status === 'inadequate' ? '⚠️' :
                         tc.status === 'missing' ? '❌' : '➖';
      const statusLabel = tc.status.replace('-', ' ').toUpperCase();
      lines.push('### 🧪 Test Coverage Status', '');
      lines.push('| Category | Status | Details |', '|---|---|---|');

      const authBillingAdmin = tc.missingTestFiles.some(f =>
        f.includes('auth/') || f.includes('billing/') || f.includes('admin/')
      );
      const featureTested = tc.testFilesChanged > 0 && tc.criticalFeaturesTested;
      const deletedTests = tc.deletedTestFiles.length > 0;

      lines.push(
        `| Auth/Billing/Admin changes | ${authBillingAdmin ? '⚠️ NO TESTS' : '✅ TESTED'} | ${authBillingAdmin ? 'Critical path changed, no test files modified' : 'Test files updated for critical paths'} |`,
        `| Feature code changes | ${featureTested ? '✅ TESTED' : '⚠️ PARTIAL'} | ${tc.testFilesChanged} test file(s) updated |`,
        `| Deleted tests | ${deletedTests ? '❌ DELETED' : '✅ NONE'} | ${deletedTests ? tc.deletedTestFiles.join(', ') : 'No test files deleted'} |`
      );
      lines.push('');
    }

    // Exact Reproduction Commands
    lines.push('### 🔧 Reproduction Commands', '');
    lines.push('```bash');
    lines.push('# Review this diff');
    lines.push(`turpan review . --from ${diffReview.baseRef} --to ${diffReview.targetRef}`);
    lines.push('');
    lines.push('# Deep diff analysis');
    lines.push(`turpan review . --from ${diffReview.baseRef} --to ${diffReview.targetRef} --deep`);
    lines.push('');
    lines.push('# Scoped agent audit');
    lines.push(`turpan agent-audit . --task ./task.md --from ${diffReview.baseRef} --to ${diffReview.targetRef}`);
    lines.push('```', '');

    // Findings
    if (diffReview.findingsIntroducedByDiff.length > 0) {
      lines.push('### 🔍 Findings in Diff', '');
      for (const f of diffReview.findingsIntroducedByDiff) lines.push(`- ${f}`);
      lines.push('');
    }

    // Top findings summary
    if (findings.length > 0) {
      lines.push('### 🔎 Top Findings', '');
      const top = findings.slice(0, 10);
      for (const f of top) {
        const icon = f.severity === 'critical' ? '🔴' :
                     f.severity === 'high' ? '🟠' :
                     f.severity === 'medium' ? '🟡' : '🔵';
        lines.push(`${icon} **${f.severity.toUpperCase()}** \`[${f.category}]\` ${f.title}`);
        if (f.file) lines.push(`   └─ ${f.file}${f.line ? `:${f.line}` : ''}`);
      }
      if (findings.length > 10) {
        lines.push(`_…and ${findings.length - 10} more findings._`);
      }
      lines.push('');
    } else {
      lines.push('### 🔎 Findings', '');
      lines.push('_No findings in this diff._', '');
    }

    // Footer
    lines.push('---', '');
    lines.push('_🤖 Generated by [Turpan](https://github.com/turpan/turpan) — PR review agent_', '');

    return lines.join('\n');
  }
}