// Placeholder/fake implementation detector fixture
// This file contains various placeholder patterns

// TODO without follow-up
function processData(data: unknown) {
  // coming soon: full implementation
  console.log('Processing data...', data);
  return data;
}

// throw new Error not implemented
function unimplementedFeature() {
  throw new Error('Not implemented yet');
}

// Hardcoded success return
async function mockApiCall(): Promise<{ success: boolean }> {
  console.log('API call would happen here');
  return { success: true }; // mock
}

// Demo only implementation
function calculateTotal(items: number[]): number {
  // demo only - real implementation needed
  return 999;
}

// Agent output marker
// Generated by AI assistant on 2024-01-15
interface Config {
  apiUrl: string;
  timeout: number;
}

// This looks like a placeholder
const config: Config = {
  apiUrl: 'http://localhost:3000', // TODO: make configurable
  timeout: 5000,
};

export { processData, unimplementedFeature, mockApiCall, calculateTotal, config };
